import { buildLocalizedContent } from "./build";
export const content = buildLocalizedContent({
  categoryNames:{lifePath:"Lebensweg",expression:"Ausdruck",soulUrge:"Seelenwunsch",personality:"Persönlichkeit",personalYear:"Persönliches Jahr"},
  numberThemes:{1:["Unabhängigkeit","Führung","Originalität"],2:["Zusammenarbeit","Sensibilität","Balance"],3:["Kreativität","Ausdruck","Freude"],4:["Stabilität","Disziplin","Pragmatismus"],5:["Freiheit","Veränderung","Abenteuer"],6:["Verantwortung","Liebe","Harmonie"],7:["Weisheit","Innenschau","Analyse"],8:["Kraft","Erfolg","Autorität"],9:["Mitgefühl","Humanität","Vollendung"],11:["Intuition","Inspiration","Erleuchtung"],22:["Vision","Meisterschaft","Vermächtnis"],33:["Heilung","Dienst","bedingungslose Liebe"]},
  numberBrief:(category,number,themes)=>`${category} ${number} betont ${themes.join(", ")}. Wenn du diese Energie ausgewogen integrierst, werden ihre Stärken besonders deutlich.`,
  signNames:{Aries:"Widder",Taurus:"Stier",Gemini:"Zwillinge",Cancer:"Krebs",Leo:"Löwe",Virgo:"Jungfrau",Libra:"Waage",Scorpio:"Skorpion",Sagittarius:"Schütze",Capricorn:"Steinbock",Aquarius:"Wassermann",Pisces:"Fische"},
  signTraits:{Aries:["mutig","entschlossen","leidenschaftlich"],Taurus:["zuverlässig","geduldig","praktisch"],Gemini:["neugierig","anpassungsfähig","kommunikativ"],Cancer:["intuitiv","beschützend","loyal"],Leo:["kreativ","großzügig","selbstbewusst"],Virgo:["analytisch","gewissenhaft","zuverlässig"],Libra:["diplomatisch","fair","gesellig"],Scorpio:["leidenschaftlich","wahrnehmungsstark","entschlossen"],Sagittarius:["abenteuerlustig","optimistisch","philosophisch"],Capricorn:["diszipliniert","verantwortungsvoll","strategisch"],Aquarius:["originell","unabhängig","fortschrittlich"],Pisces:["mitfühlend","intuitiv","künstlerisch"]},
  signDescription:(sign,traits)=>`${sign} wird mit einer ${traits.join(", ")} geprägten Energie verbunden. Diese Qualitäten prägen deine natürliche Art, der Welt zu begegnen.`,
  elementNames:{Fire:"Feuer",Water:"Wasser",Earth:"Erde",Air:"Luft",Wood:"Holz",Metal:"Metall"},modalityNames:{Cardinal:"Kardinal",Fixed:"Fix",Mutable:"Veränderlich"},
  planetNames:{Mars:"Mars",Venus:"Venus",Mercury:"Merkur",Moon:"Mond",Sun:"Sonne",Pluto:"Pluto",Jupiter:"Jupiter",Saturn:"Saturn",Uranus:"Uranus",Neptune:"Neptun"},
  animalNames:{Rat:"Ratte",Ox:"Ochse",Tiger:"Tiger",Rabbit:"Hase",Dragon:"Drache",Snake:"Schlange",Horse:"Pferd",Goat:"Ziege",Monkey:"Affe",Rooster:"Hahn",Dog:"Hund",Pig:"Schwein"},
  animalTraits:{Rat:["schlagfertig","anpassungsfähig","chancenorientiert"],Ox:["fleißig","zuverlässig","stark"],Tiger:["mutig","wettbewerbsorientiert","magnetisch"],Rabbit:["sanft","elegant","feinfühlig"],Dragon:["ehrgeizig","energisch","furchtlos"],Snake:["weise","intuitiv","rätselhaft"],Horse:["energisch","freiheitsliebend","warm"],Goat:["kreativ","sanft","mitfühlend"],Monkey:["clever","erfinderisch","verspielt"],Rooster:["beobachtend","fleißig","mutig"],Dog:["loyal","ehrlich","freundlich"],Pig:["großzügig","mitfühlend","aufrichtig"]},
  animalDescription:(animal,traits)=>`${animal} gilt als ${traits.join(", ")}. In der chinesischen Astrologie symbolisiert dieses Zeichen deinen natürlichen Rhythmus und deine instinktive Art zu handeln.`,
  chineseElementNames:{Wood:"Holz",Fire:"Feuer",Earth:"Erde",Metal:"Metall",Water:"Wasser"},
  chineseElementDescriptions:{Wood:"Energie von Wachstum, Kreativität und Flexibilität.",Fire:"Energie von Leidenschaft, Dynamik und Führung.",Earth:"Energie von Stabilität, Fürsorge und Pragmatismus.",Metal:"Energie von Präzision, Entschlossenheit und Stärke.",Water:"Energie von Weisheit, Intuition und Anpassungsfähigkeit."},yinYang:{Yin:"Yin",Yang:"Yang"},
});
