import { buildLocalizedContent } from "./build";
export const content = buildLocalizedContent({
  categoryNames:{lifePath:"Camino de Vida",expression:"Expresión",soulUrge:"Impulso del Alma",personality:"Personalidad",personalYear:"Año Personal"},
  numberThemes:{1:["independencia","liderazgo","originalidad"],2:["cooperación","sensibilidad","equilibrio"],3:["creatividad","expresión","alegría"],4:["estabilidad","disciplina","practicidad"],5:["libertad","cambio","aventura"],6:["responsabilidad","amor","armonía"],7:["sabiduría","introspección","análisis"],8:["poder","logro","autoridad"],9:["compasión","humanitarismo","culminación"],11:["intuición","inspiración","iluminación"],22:["visión","maestría","legado"],33:["sanación","servicio","amor incondicional"]},
  numberBrief:(category,number,themes)=>`${category} ${number} pone el foco en ${themes.join(", ")}. Cuando integras esta energía con equilibrio, sus fortalezas se vuelven especialmente visibles.`,
  signNames:{Aries:"Aries",Taurus:"Tauro",Gemini:"Géminis",Cancer:"Cáncer",Leo:"Leo",Virgo:"Virgo",Libra:"Libra",Scorpio:"Escorpio",Sagittarius:"Sagitario",Capricorn:"Capricornio",Aquarius:"Acuario",Pisces:"Piscis"},
  signTraits:{Aries:["valiente","decidido","apasionado"],Taurus:["fiable","paciente","práctico"],Gemini:["curioso","adaptable","comunicativo"],Cancer:["intuitivo","protector","leal"],Leo:["creativo","generoso","seguro"],Virgo:["analítico","diligente","fiable"],Libra:["diplomático","justo","social"],Scorpio:["apasionado","perceptivo","decidido"],Sagittarius:["aventurero","optimista","filosófico"],Capricorn:["disciplinado","responsable","estratégico"],Aquarius:["original","independiente","progresista"],Pisces:["compasivo","intuitivo","artístico"]},
  signDescription:(sign,traits)=>`${sign} se asocia con una forma de ser ${traits.join(", ")}. Su energía resalta estas cualidades en la manera de relacionarte con el mundo.`,
  elementNames:{Fire:"Fuego",Water:"Agua",Earth:"Tierra",Air:"Aire",Wood:"Madera",Metal:"Metal"},modalityNames:{Cardinal:"Cardinal",Fixed:"Fija",Mutable:"Mutable"},
  planetNames:{Mars:"Marte",Venus:"Venus",Mercury:"Mercurio",Moon:"Luna",Sun:"Sol",Pluto:"Plutón",Jupiter:"Júpiter",Saturn:"Saturno",Uranus:"Urano",Neptune:"Neptuno"},
  animalNames:{Rat:"Rata",Ox:"Buey",Tiger:"Tigre",Rabbit:"Conejo",Dragon:"Dragón",Snake:"Serpiente",Horse:"Caballo",Goat:"Cabra",Monkey:"Mono",Rooster:"Gallo",Dog:"Perro",Pig:"Cerdo"},
  animalTraits:{Rat:["ingeniosa","adaptable","oportunista"],Ox:["trabajador","fiable","fuerte"],Tiger:["valiente","competitivo","magnético"],Rabbit:["amable","elegante","perceptivo"],Dragon:["ambicioso","enérgico","audaz"],Snake:["sabio","intuitivo","enigmático"],Horse:["enérgico","libre","cálido"],Goat:["creativo","amable","compasivo"],Monkey:["ingenioso","inventivo","juguetón"],Rooster:["observador","trabajador","valiente"],Dog:["leal","honesto","amable"],Pig:["generoso","compasivo","sincero"]},
  animalDescription:(animal,traits)=>`${animal} se describe como ${traits.join(", ")}. En la astrología china simboliza tu ritmo natural y tu forma instintiva de moverte por el mundo.`,
  chineseElementNames:{Wood:"Madera",Fire:"Fuego",Earth:"Tierra",Metal:"Metal",Water:"Agua"},
  chineseElementDescriptions:{Wood:"Energía de crecimiento, creatividad y flexibilidad.",Fire:"Energía de pasión, dinamismo y liderazgo.",Earth:"Energía de estabilidad, cuidado y practicidad.",Metal:"Energía de precisión, determinación y fuerza.",Water:"Energía de sabiduría, intuición y adaptabilidad."},yinYang:{Yin:"Yin",Yang:"Yang"},
});
