import { buildLocalizedContent } from "./build";
export const content = buildLocalizedContent({
  categoryNames:{lifePath:"Chemin de Vie",expression:"Expression",soulUrge:"Élan de l'Âme",personality:"Personnalité",personalYear:"Année Personnelle"},
  numberThemes:{1:["indépendance","leadership","originalité"],2:["coopération","sensibilité","équilibre"],3:["créativité","expression","joie"],4:["stabilité","discipline","pragmatisme"],5:["liberté","changement","aventure"],6:["responsabilité","amour","harmonie"],7:["sagesse","introspection","analyse"],8:["pouvoir","accomplissement","autorité"],9:["compassion","humanisme","accomplissement"],11:["intuition","inspiration","illumination"],22:["vision","maîtrise","héritage"],33:["guérison","service","amour inconditionnel"]},
  numberBrief:(category,number,themes)=>`${category} ${number} met l'accent sur ${themes.join(", ")}. Lorsque cette énergie est intégrée avec équilibre, ses forces deviennent particulièrement visibles.`,
  signNames:{Aries:"Bélier",Taurus:"Taureau",Gemini:"Gémeaux",Cancer:"Cancer",Leo:"Lion",Virgo:"Vierge",Libra:"Balance",Scorpio:"Scorpion",Sagittarius:"Sagittaire",Capricorn:"Capricorne",Aquarius:"Verseau",Pisces:"Poissons"},
  signTraits:{Aries:["courageux","déterminé","passionné"],Taurus:["fiable","patient","pragmatique"],Gemini:["curieux","adaptable","communicatif"],Cancer:["intuitif","protecteur","loyal"],Leo:["créatif","généreux","confiant"],Virgo:["analytique","appliqué","fiable"],Libra:["diplomate","équitable","sociable"],Scorpio:["passionné","lucide","déterminé"],Sagittarius:["aventureux","optimiste","philosophe"],Capricorn:["discipliné","responsable","stratégique"],Aquarius:["original","indépendant","progressiste"],Pisces:["compatissant","intuitif","artistique"]},
  signDescription:(sign,traits)=>`${sign} est associé à une énergie ${traits.join(", ")}. Ces qualités colorent votre manière naturelle d'aborder le monde.`,
  elementNames:{Fire:"Feu",Water:"Eau",Earth:"Terre",Air:"Air",Wood:"Bois",Metal:"Métal"},modalityNames:{Cardinal:"Cardinal",Fixed:"Fixe",Mutable:"Mutable"},
  planetNames:{Mars:"Mars",Venus:"Vénus",Mercury:"Mercure",Moon:"Lune",Sun:"Soleil",Pluto:"Pluton",Jupiter:"Jupiter",Saturn:"Saturne",Uranus:"Uranus",Neptune:"Neptune"},
  animalNames:{Rat:"Rat",Ox:"Bœuf",Tiger:"Tigre",Rabbit:"Lapin",Dragon:"Dragon",Snake:"Serpent",Horse:"Cheval",Goat:"Chèvre",Monkey:"Singe",Rooster:"Coq",Dog:"Chien",Pig:"Cochon"},
  animalTraits:{Rat:["vif","adaptable","opportuniste"],Ox:["travailleur","fiable","fort"],Tiger:["courageux","compétitif","magnétique"],Rabbit:["doux","élégant","perceptif"],Dragon:["ambitieux","énergique","audacieux"],Snake:["sage","intuitif","énigmatique"],Horse:["énergique","libre","chaleureux"],Goat:["créatif","doux","compatissant"],Monkey:["ingénieux","inventif","espiègle"],Rooster:["observateur","travailleur","courageux"],Dog:["loyal","honnête","bienveillant"],Pig:["généreux","compatissant","sincère"]},
  animalDescription:(animal,traits)=>`${animal} est décrit comme ${traits.join(", ")}. En astrologie chinoise, ce signe symbolise votre rythme naturel et votre manière instinctive d'agir.`,
  chineseElementNames:{Wood:"Bois",Fire:"Feu",Earth:"Terre",Metal:"Métal",Water:"Eau"},
  chineseElementDescriptions:{Wood:"Énergie de croissance, de créativité et de souplesse.",Fire:"Énergie de passion, de dynamisme et de leadership.",Earth:"Énergie de stabilité, de soutien et de pragmatisme.",Metal:"Énergie de précision, de détermination et de force.",Water:"Énergie de sagesse, d'intuition et d'adaptabilité."},yinYang:{Yin:"Yin",Yang:"Yang"},
});
