import { buildLocalizedContent } from "./build";
export const content = buildLocalizedContent({
  categoryNames:{lifePath:"Percorso di Vita",expression:"Espressione",soulUrge:"Desiderio dell'Anima",personality:"Personalità",personalYear:"Anno Personale"},
  numberThemes:{1:["indipendenza","leadership","originalità"],2:["cooperazione","sensibilità","equilibrio"],3:["creatività","espressione","gioia"],4:["stabilità","disciplina","praticità"],5:["libertà","cambiamento","avventura"],6:["responsabilità","amore","armonia"],7:["saggezza","introspezione","analisi"],8:["potere","realizzazione","autorità"],9:["compassione","umanitarismo","completamento"],11:["intuizione","ispirazione","illuminazione"],22:["visione","maestria","eredità"],33:["guarigione","servizio","amore incondizionato"]},
  numberBrief:(category,number,themes)=>`${category} ${number} mette in evidenza ${themes.join(", ")}. Quando integri questa energia con equilibrio, i suoi punti di forza diventano particolarmente visibili.`,
  signNames:{Aries:"Ariete",Taurus:"Toro",Gemini:"Gemelli",Cancer:"Cancro",Leo:"Leone",Virgo:"Vergine",Libra:"Bilancia",Scorpio:"Scorpione",Sagittarius:"Sagittario",Capricorn:"Capricorno",Aquarius:"Acquario",Pisces:"Pesci"},
  signTraits:{Aries:["coraggioso","determinato","appassionato"],Taurus:["affidabile","paziente","pratico"],Gemini:["curioso","adattabile","comunicativo"],Cancer:["intuitivo","protettivo","leale"],Leo:["creativo","generoso","sicuro"],Virgo:["analitico","diligente","affidabile"],Libra:["diplomatico","equo","socievole"],Scorpio:["appassionato","percettivo","determinato"],Sagittarius:["avventuroso","ottimista","filosofico"],Capricorn:["disciplinato","responsabile","strategico"],Aquarius:["originale","indipendente","progressista"],Pisces:["compassionevole","intuitivo","artistico"]},
  signDescription:(sign,traits)=>`${sign} è associato a un'energia ${traits.join(", ")}. Queste qualità caratterizzano il tuo modo naturale di entrare in relazione con il mondo.`,
  elementNames:{Fire:"Fuoco",Water:"Acqua",Earth:"Terra",Air:"Aria",Wood:"Legno",Metal:"Metallo"},modalityNames:{Cardinal:"Cardinale",Fixed:"Fissa",Mutable:"Mutevole"},
  planetNames:{Mars:"Marte",Venus:"Venere",Mercury:"Mercurio",Moon:"Luna",Sun:"Sole",Pluto:"Plutone",Jupiter:"Giove",Saturn:"Saturno",Uranus:"Urano",Neptune:"Nettuno"},
  animalNames:{Rat:"Topo",Ox:"Bue",Tiger:"Tigre",Rabbit:"Coniglio",Dragon:"Drago",Snake:"Serpente",Horse:"Cavallo",Goat:"Capra",Monkey:"Scimmia",Rooster:"Gallo",Dog:"Cane",Pig:"Maiale"},
  animalTraits:{Rat:["arguto","adattabile","opportunista"],Ox:["laborioso","affidabile","forte"],Tiger:["coraggioso","competitivo","magnetico"],Rabbit:["gentile","elegante","percettivo"],Dragon:["ambizioso","energico","impavido"],Snake:["saggio","intuitivo","enigmatico"],Horse:["energico","libero","caloroso"],Goat:["creativo","gentile","compassionevole"],Monkey:["intelligente","inventivo","giocoso"],Rooster:["osservatore","laborioso","coraggioso"],Dog:["leale","onesto","gentile"],Pig:["generoso","compassionevole","sincero"]},
  animalDescription:(animal,traits)=>`${animal} viene descritto come ${traits.join(", ")}. Nell'astrologia cinese questo segno simboleggia il tuo ritmo naturale e il tuo modo istintivo di agire.`,
  chineseElementNames:{Wood:"Legno",Fire:"Fuoco",Earth:"Terra",Metal:"Metallo",Water:"Acqua"},
  chineseElementDescriptions:{Wood:"Energia di crescita, creatività e flessibilità.",Fire:"Energia di passione, dinamismo e leadership.",Earth:"Energia di stabilità, nutrimento e praticità.",Metal:"Energia di precisione, determinazione e forza.",Water:"Energia di saggezza, intuizione e adattabilità."},yinYang:{Yin:"Yin",Yang:"Yang"},
});
