import { buildLocalizedContent } from "./build";
export const content = buildLocalizedContent({
  categoryNames:{lifePath:"Caminho de Vida",expression:"Expressão",soulUrge:"Desejo da Alma",personality:"Personalidade",personalYear:"Ano Pessoal"},
  numberThemes:{1:["independência","liderança","originalidade"],2:["cooperação","sensibilidade","equilíbrio"],3:["criatividade","expressão","alegria"],4:["estabilidade","disciplina","praticidade"],5:["liberdade","mudança","aventura"],6:["responsabilidade","amor","harmonia"],7:["sabedoria","introspeção","análise"],8:["poder","realização","autoridade"],9:["compaixão","humanitarismo","conclusão"],11:["intuição","inspiração","iluminação"],22:["visão","mestria","legado"],33:["cura","serviço","amor incondicional"]},
  numberBrief:(category,number,themes)=>`${category} ${number} destaca ${themes.join(", ")}. Quando esta energia é integrada com equilíbrio, as suas forças tornam-se especialmente visíveis.`,
  signNames:{Aries:"Carneiro",Taurus:"Touro",Gemini:"Gémeos",Cancer:"Caranguejo",Leo:"Leão",Virgo:"Virgem",Libra:"Balança",Scorpio:"Escorpião",Sagittarius:"Sagitário",Capricorn:"Capricórnio",Aquarius:"Aquário",Pisces:"Peixes"},
  signTraits:{Aries:["corajoso","determinado","apaixonado"],Taurus:["fiável","paciente","prático"],Gemini:["curioso","adaptável","comunicativo"],Cancer:["intuitivo","protetor","leal"],Leo:["criativo","generoso","confiante"],Virgo:["analítico","diligente","fiável"],Libra:["diplomático","justo","social"],Scorpio:["apaixonado","perceptivo","determinado"],Sagittarius:["aventureiro","otimista","filosófico"],Capricorn:["disciplinado","responsável","estratégico"],Aquarius:["original","independente","progressista"],Pisces:["compassivo","intuitivo","artístico"]},
  signDescription:(sign,traits)=>`${sign} associa-se a uma energia ${traits.join(", ")}. Estas qualidades moldam a sua forma natural de se relacionar com o mundo.`,
  elementNames:{Fire:"Fogo",Water:"Água",Earth:"Terra",Air:"Ar",Wood:"Madeira",Metal:"Metal"},modalityNames:{Cardinal:"Cardinal",Fixed:"Fixa",Mutable:"Mutável"},
  planetNames:{Mars:"Marte",Venus:"Vénus",Mercury:"Mercúrio",Moon:"Lua",Sun:"Sol",Pluto:"Plutão",Jupiter:"Júpiter",Saturn:"Saturno",Uranus:"Urano",Neptune:"Neptuno"},
  animalNames:{Rat:"Rato",Ox:"Boi",Tiger:"Tigre",Rabbit:"Coelho",Dragon:"Dragão",Snake:"Serpente",Horse:"Cavalo",Goat:"Cabra",Monkey:"Macaco",Rooster:"Galo",Dog:"Cão",Pig:"Porco"},
  animalTraits:{Rat:["perspicaz","adaptável","oportunista"],Ox:["trabalhador","fiável","forte"],Tiger:["corajoso","competitivo","magnético"],Rabbit:["gentil","elegante","perceptivo"],Dragon:["ambicioso","enérgico","destemido"],Snake:["sábio","intuitivo","enigmático"],Horse:["enérgico","livre","caloroso"],Goat:["criativo","gentil","compassivo"],Monkey:["esperto","inventivo","brincalhão"],Rooster:["observador","trabalhador","corajoso"],Dog:["leal","honesto","bondoso"],Pig:["generoso","compassivo","sincero"]},
  animalDescription:(animal,traits)=>`${animal} é descrito como ${traits.join(", ")}. Na astrologia chinesa, este signo simboliza o seu ritmo natural e a sua forma instintiva de agir.`,
  chineseElementNames:{Wood:"Madeira",Fire:"Fogo",Earth:"Terra",Metal:"Metal",Water:"Água"},
  chineseElementDescriptions:{Wood:"Energia de crescimento, criatividade e flexibilidade.",Fire:"Energia de paixão, dinamismo e liderança.",Earth:"Energia de estabilidade, cuidado e praticidade.",Metal:"Energia de precisão, determinação e força.",Water:"Energia de sabedoria, intuição e adaptabilidade."},yinYang:{Yin:"Yin",Yang:"Yang"},
});
