import type { Locale } from './i18n/locales';
import { atlasCopy } from './i18n/atlas';
import type { ReadingInput } from './profile';
import type { ParsedAnalysis } from './analysis-stream';

/** One consistent fictional fixture. Never stored over the visitor's own details. */
export const SAMPLE_INPUT: ReadingInput = { fullName: 'Alex Morgan', dateOfBirth: '1990-11-04', lifeStages: ['building_career', 'in_relationship'] };
const stories: Record<Locale, [string, string, string, string[]]> = {
  en: [
    'You’re drawn to what lies beneath the surface. Your numbers and Scorpio Sun suggest a reflective streak; the Horse brings a desire for movement. This chapter may be about making room for both.',
    'Your Life Path 7 and Scorpio Sun both invite a closer look. In a career-building chapter, that can mean asking the question that others move past too quickly. Consider where careful attention already makes your work feel worthwhile. Your Expression 11 adds a traditional theme of sensitivity: an idea may matter to you before you can explain why. Let that be a starting point for inquiry, rather than proof that it must be right.',
    'The Horse’s appetite for movement sits beside your quieter, investigative streak. You may need both an open horizon and a room where you can think. Your Soul Urge 4 adds a wish for stability. These themes need not cancel one another out: a reliable routine can give an experiment room to unfold. In a relationship, try naming when you need quiet and when you want company, rather than hoping someone will read the difference.',
    ['Keep a question journal for seven days.', 'Protect one hour for uninterrupted study.', 'Try a small change before a large commitment.'],
  ],
  tr: ['Sayıların ve Akrep Güneşi düşünmeye dönük bir eğilimi, At ise hareket arzusunu çağrıştırıyor. Bu dönem her ikisine de yer açmakla ilgili olabilir.', 'Yaşam Yolu 7 ve Akrep Güneşi yakından bakmaya davet eder. Kariyerinde, başkalarının hızla geçtiği bir soruya zaman ayırmayı deneyebilirsin. İfade 11’in duyarlılık teması, ilk sezgini araştırma için bir başlangıç yapabilir.', 'At’ın hareket arzusu ile daha sessiz, araştırmacı yanın birlikte var olabilir. Ruh Arzusu 4 istikrar ihtiyacını ekler. Güvenilir bir rutin denemelerine alan açabilir. İlişkinde ne zaman yalnızlığa, ne zaman yakınlığa ihtiyaç duyduğunu dile getirmeyi dene.', ['Yedi gün boyunca sorularını not et.', 'Kesintisiz çalışmak için bir saat ayır.', 'Büyük bir karar öncesi küçük bir değişiklik dene.']],
  es: ['Tus números y tu Sol en Escorpio sugieren una tendencia reflexiva; el Caballo aporta deseo de movimiento. Esta etapa puede dar espacio a ambos.', 'Tu Camino de Vida 7 y tu Sol en Escorpio invitan a mirar más de cerca. En tu carrera, prueba dedicar tiempo a una pregunta que otros pasan por alto. La sensibilidad asociada a tu Expresión 11 puede ser un punto de partida para investigar.', 'El deseo de movimiento del Caballo puede convivir con tu faceta más silenciosa. Tu Impulso del Alma 4 añade una necesidad de estabilidad. Una rutina fiable puede abrir espacio a los experimentos. En pareja, expresa cuándo necesitas silencio y cuándo compañía.', ['Lleva un diario de preguntas durante siete días.', 'Reserva una hora de estudio sin interrupciones.', 'Prueba un pequeño cambio antes de un gran compromiso.']],
  fr: ['Vos nombres et votre Soleil en Scorpion suggèrent un côté réfléchi ; le Cheval apporte un désir de mouvement. Ce chapitre peut accueillir les deux.', 'Votre Chemin de Vie 7 et votre Soleil en Scorpion invitent à regarder de plus près. Dans votre carrière, prenez le temps d’examiner une question que les autres survolent. La sensibilité associée à votre Expression 11 peut devenir un point de départ pour explorer.', 'Le désir de mouvement du Cheval peut coexister avec votre côté plus silencieux. Votre Élan de l’Âme 4 ajoute un besoin de stabilité. Une routine fiable peut laisser place aux essais. Dans votre relation, exprimez quand vous avez besoin de calme ou de compagnie.', ['Tenez un carnet de questions pendant sept jours.', 'Réservez une heure d’étude sans interruption.', 'Essayez un petit changement avant un grand engagement.']],
  de: ['Deine Zahlen und deine Skorpion-Sonne deuten auf eine nachdenkliche Seite hin; das Pferd steht für Bewegung. Dieses Kapitel könnte beiden Raum geben.', 'Dein Lebensweg 7 und deine Skorpion-Sonne laden zum genauen Hinsehen ein. Nimm dir beruflich Zeit für eine Frage, an der andere vorbeigehen. Die mit deiner Ausdruckszahl 11 verbundene Sensibilität kann ein Ausgangspunkt für weitere Erkundung sein.', 'Der Bewegungsdrang des Pferdes kann neben deiner stilleren Seite bestehen. Deine Seelenzahl 4 bringt ein Bedürfnis nach Stabilität hinzu. Eine verlässliche Routine kann Raum für Experimente schaffen. Sprich in deiner Beziehung aus, wann du Ruhe und wann du Gesellschaft brauchst.', ['Führe sieben Tage lang ein Fragenjournal.', 'Reserviere eine Stunde zum ungestörten Lernen.', 'Probiere eine kleine Veränderung vor einer großen Verpflichtung.']],
  pt: ['Seus números e seu Sol em Escorpião sugerem um lado reflexivo; o Cavalo traz desejo de movimento. Esta fase pode abrir espaço para ambos.', 'Seu Caminho de Vida 7 e seu Sol em Escorpião convidam a olhar mais de perto. Na carreira, dedique tempo a uma pergunta que outros deixam passar. A sensibilidade associada à sua Expressão 11 pode ser um ponto de partida para investigar.', 'O desejo de movimento do Cavalo pode conviver com seu lado mais silencioso. Seu Desejo da Alma 4 acrescenta uma necessidade de estabilidade. Uma rotina confiável pode abrir espaço para experiências. No relacionamento, diga quando precisa de silêncio ou companhia.', ['Anote suas perguntas durante sete dias.', 'Reserve uma hora de estudo sem interrupções.', 'Experimente uma pequena mudança antes de um grande compromisso.']],
  it: ['I tuoi numeri e il Sole in Scorpione suggeriscono un lato riflessivo; il Cavallo porta desiderio di movimento. Questo capitolo può fare spazio a entrambi.', 'Il tuo Percorso di Vita 7 e il Sole in Scorpione invitano a guardare più da vicino. Nel lavoro, dedica tempo a una domanda che altri trascurano. La sensibilità associata alla tua Espressione 11 può essere un punto di partenza per esplorare.', 'Il desiderio di movimento del Cavallo può convivere con il tuo lato più silenzioso. Il Desiderio dell’Anima 4 aggiunge un bisogno di stabilità. Una routine affidabile può lasciare spazio agli esperimenti. Nella relazione, esprimi quando hai bisogno di quiete o di compagnia.', ['Tieni un diario di domande per sette giorni.', 'Riserva un’ora allo studio senza interruzioni.', 'Prova un piccolo cambiamento prima di un grande impegno.']],
};
export function getSampleAnalysis(locale: Locale): ParsedAnalysis {
  const c = atlasCopy[locale], [snapshot, shared, tensions, toolkit] = stories[locale];
  return { cosmicSnapshot: snapshot, combinedAnalysis: `## ${c.shared}\n\n${shared}\n\n## ${c.tensions}\n\n${tensions}\n\n## ${c.practical}\n\n${toolkit.join(' ')}`, currentSeason: null, cosmicToolkit: toolkit };
}
