import type { Locale } from './locales';

const en = {
  eyebrow: 'Many systems. One you.',
  headline: 'The patterns that make you,', headlineEnd: 'you.',
  description: 'Explore how your numbers, birth chart, and life’s current chapter connect.',
  discover: 'Discover your reading', sample: 'Explore a sample', sampleLabel: 'Sample reading',
  glimpse: 'A glimpse inside', seal: 'The atlas seal / A symbol of connection',
  insight: 'Your Life Path 7 and Scorpio Sun share an instinct to look beneath the surface. Give your curiosity a place to go.',
  beginnings: 'Let’s start with your beginnings.', chapter: 'What chapter are you in?',
  birthHelper: 'A few details to begin connecting the threads.', chapterHelper: 'Life rarely fits one box. Choose all that feel true.',
  unknown: 'Without a birth time, we omit Moon, rising, and houses and show an approximate solar chart.',
  privacy: 'Your form stays in this browser session. OpenRouter and its model providers process your profile to write the interpretation. Generated readings may be cached in server memory for up to 24 hours.',
  reflection: 'A framework for reflection, not a prediction.', edit: 'Edit details', atlasOf: 'The atlas of {name}.',
  sharePreview: 'Share preview', sharePrivacy: 'Only these identity markers and the site link will be copied. Your name, birth date, time, place, and personal context are excluded.',
  copy: 'Copy summary and link', close: 'Close', ready: 'Your calculated profile is ready to explore. Your interpretation will connect these threads.',
  chartPrecision: 'Sign-level diagram: markers show calculated signs, not exact degrees. Houses, planetary aspects, and current transits are not calculated.',
  solar: 'Approximate solar chart', knownChart: 'Your chart, by sign',
  partial: 'Your interpretation couldn’t finish. Your calculated profile and any text already received are still available.',
  toolkitPending: 'Your practical takeaways will appear when the interpretation is ready.',
  seasonNote: 'Based on your Personal Year. No current planetary transits are calculated.',
  shared: 'The thread that runs through', tensions: 'Room for two instincts', practical: 'Make it practical',
};
type AtlasCopy = { [K in keyof typeof en]: string };
export const atlasCopy: Record<Locale, AtlasCopy> = {
  en,
  tr: {
    eyebrow:'Birçok sistem. Tek bir sen.', headline:'Seni sen yapan',headlineEnd:'örüntüler.',description:'Sayıların, doğum haritan ve hayatının bu döneminin nasıl birleştiğini keşfet.',discover:'Kozmik haritanı keşfet',sample:'Örneği incele',sampleLabel:'Örnek okuma',glimpse:'İçeriden bir bakış',seal:'Atlas mührü / Bağlantının simgesi',insight:'Yaşam Yolu 7 ve Akrep Güneşi, yüzeyin altına bakma eğilimini paylaşır. Merakına alan aç.',beginnings:'Başlangıcından başlayalım.',chapter:'Hayatının hangi dönemindesin?',birthHelper:'Bağlantıları kurmaya başlamak için birkaç bilgi.',chapterHelper:'Hayat tek bir kutuya sığmaz. Sana uyanların tümünü seç.',unknown:'Doğum saati olmadan Ay, yükselen ve evleri göstermeyiz; yaklaşık bir Güneş haritası sunarız.',privacy: 'Formun bu tarayıcı oturumunda kalır. OpenRouter ve model sağlayıcıları yorum için profilini işler. Üretilen okumalar sunucu belleğinde 24 saate kadar tutulabilir.',reflection:'Bir düşünme çerçevesi, bir kehanet değil.',edit:'Bilgileri düzenle',atlasOf:'{name} için bir atlas.',sharePreview:'Paylaşım önizlemesi',sharePrivacy:'Yalnızca bu göstergeler ve site bağlantısı kopyalanır. Adın, doğum tarihin, saatin, yerin ve kişisel bağlamın dahil edilmez.',copy:'Özeti ve bağlantıyı kopyala',close:'Kapat',ready:'Hesaplanan profilin hazır. Yorumun bu bağlantıları bir araya getirecek.',chartPrecision:'Burç düzeyinde şema: işaretler kesin dereceleri değil, hesaplanan burçları gösterir. Evler, gezegen açıları ve güncel transitler hesaplanmaz.',solar:'Yaklaşık Güneş haritası',knownChart:'Burçlara göre haritan',partial:'Yorumun tamamlanamadı. Hesaplanan profilin ve gelen metin kullanılabilir durumda.',toolkitPending:'Pratik önerilerin yorum hazır olduğunda görünecek.',seasonNote:'Kişisel Yıl sayına dayanır. Güncel gezegen transitleri hesaplanmaz.',shared:'Ortak bir iz',tensions:'İki eğilime de yer aç',practical:'Hayata geçir',
  },
  es: {
    eyebrow:'Varios sistemas. Una sola persona.',headline:'Los patrones que te hacen',headlineEnd:'ser tú.',description:'Explora cómo se conectan tus números, tu carta natal y tu etapa vital.',discover:'Descubre tu mapa',sample:'Explora un ejemplo',sampleLabel:'Lectura de ejemplo',glimpse:'Una mirada al interior',seal:'El sello del atlas / Un símbolo de conexión',insight:'Tu Camino de Vida 7 y tu Sol en Escorpio comparten el impulso de mirar bajo la superficie. Dale espacio a tu curiosidad.',beginnings:'Empecemos por tus orígenes.',chapter:'¿En qué etapa estás?',birthHelper:'Unos pocos datos para empezar a conectar los hilos.',chapterHelper:'La vida no cabe en una sola casilla. Elige todas las que te representen.',unknown:'Sin hora de nacimiento, omitimos Luna, ascendente y casas y mostramos una carta solar aproximada.',privacy: 'Tu formulario queda en esta sesión. OpenRouter y sus proveedores procesan tu perfil para la interpretación. Las lecturas pueden guardarse en la memoria del servidor hasta 24 horas.',reflection:'Un marco para reflexionar, no una predicción.',edit:'Editar datos',atlasOf:'El atlas de {name}.',sharePreview:'Vista previa para compartir',sharePrivacy:'Solo se copiarán estos indicadores y el enlace. Se excluyen tu nombre, fecha, hora, lugar de nacimiento y contexto personal.',copy:'Copiar resumen y enlace',close:'Cerrar',ready:'Tu perfil calculado está listo. Tu interpretación conectará estos hilos.',chartPrecision:'Diagrama por signos: los marcadores muestran signos calculados, no grados exactos. No se calculan casas, aspectos ni tránsitos actuales.',solar:'Carta solar aproximada',knownChart:'Tu carta por signos',partial:'La interpretación no pudo completarse. Tu perfil calculado y el texto recibido siguen disponibles.',toolkitPending:'Tus consejos prácticos aparecerán cuando la interpretación esté lista.',seasonNote:'Basado en tu Año Personal. No se calculan tránsitos planetarios actuales.',shared:'El hilo que conecta',tensions:'Espacio para dos impulsos',practical:'Llévalo a la práctica',
  },
  fr: {
    eyebrow:'Plusieurs systèmes. Une seule personne.',headline:'Les motifs qui font de vous,',headlineEnd:'vous.',description:'Explorez les liens entre vos nombres, votre thème natal et votre chapitre de vie.',discover:'Découvrez votre carte',sample:'Explorer un exemple',sampleLabel:'Lecture d’exemple',glimpse:'Un aperçu',seal:'Le sceau de l’atlas / Un symbole de connexion',insight:'Votre Chemin de Vie 7 et votre Soleil en Scorpion invitent à regarder sous la surface. Faites une place à votre curiosité.',beginnings:'Commençons par vos origines.',chapter:'Quel chapitre vivez-vous ?',birthHelper:'Quelques détails pour commencer à relier les fils.',chapterHelper:'La vie ne tient pas dans une case. Choisissez tout ce qui vous correspond.',unknown:'Sans heure de naissance, nous omettons la Lune, l’ascendant et les maisons et présentons une carte solaire approximative.',privacy: 'Votre formulaire reste dans cette session. OpenRouter et ses fournisseurs traitent votre profil pour l’interprétation. Les lectures peuvent rester en mémoire serveur pendant 24 heures maximum.',reflection:'Un cadre de réflexion, pas une prédiction.',edit:'Modifier les détails',atlasOf:'L’atlas de {name}.',sharePreview:'Aperçu du partage',sharePrivacy:'Seuls ces indicateurs et le lien seront copiés. Votre nom, date, heure et lieu de naissance et votre contexte personnel sont exclus.',copy:'Copier le résumé et le lien',close:'Fermer',ready:'Votre profil calculé est prêt. Votre interprétation reliera ces fils.',chartPrecision:'Schéma par signes : les repères indiquent les signes calculés, pas les degrés exacts. Les maisons, aspects et transits actuels ne sont pas calculés.',solar:'Carte solaire approximative',knownChart:'Votre carte par signes',partial:'L’interprétation n’a pas pu être terminée. Votre profil calculé et le texte reçu restent disponibles.',toolkitPending:'Vos conseils pratiques apparaîtront quand l’interprétation sera prête.',seasonNote:'Fondé sur votre Année Personnelle. Aucun transit planétaire actuel n’est calculé.',shared:'Le fil conducteur',tensions:'Une place pour deux élans',practical:'Passer à la pratique',
  },
  de: {
    eyebrow:'Viele Systeme. Ein Du.',headline:'Die Muster, die dich zu dem machen,',headlineEnd:'was du bist.',description:'Entdecke, wie deine Zahlen, dein Geburtshoroskop und dein Lebensabschnitt zusammenhängen.',discover:'Entdecke deinen Atlas',sample:'Beispiel ansehen',sampleLabel:'Beispieldeutung',glimpse:'Ein kleiner Einblick',seal:'Das Atlas-Siegel / Ein Symbol der Verbindung',insight:'Dein Lebensweg 7 und deine Skorpion-Sonne laden dazu ein, unter die Oberfläche zu schauen. Gib deiner Neugier Raum.',beginnings:'Beginnen wir mit deinem Anfang.',chapter:'In welchem Kapitel bist du?',birthHelper:'Ein paar Angaben, um die Verbindungen zu entdecken.',chapterHelper:'Das Leben passt selten in ein Kästchen. Wähle alles, was zutrifft.',unknown:'Ohne Geburtszeit lassen wir Mond, Aszendent und Häuser weg und zeigen ein ungefähres Sonnenhoroskop.',privacy: 'Deine Angaben bleiben in dieser Browsersitzung. OpenRouter und seine Modellanbieter verarbeiten dein Profil. Erstellte Deutungen können bis zu 24 Stunden im Serverspeicher bleiben.',reflection:'Ein Rahmen zum Nachdenken, keine Vorhersage.',edit:'Angaben bearbeiten',atlasOf:'Der Atlas von {name}.',sharePreview:'Vorschau zum Teilen',sharePrivacy:'Nur diese Merkmale und der Link werden kopiert. Name, Geburtsdatum, Zeit, Ort und persönlicher Kontext bleiben ausgeschlossen.',copy:'Zusammenfassung und Link kopieren',close:'Schließen',ready:'Dein berechnetes Profil ist bereit. Die Deutung wird diese Fäden verbinden.',chartPrecision:'Darstellung nach Zeichen: Markierungen zeigen berechnete Zeichen, keine exakten Grade. Häuser, Aspekte und aktuelle Transite werden nicht berechnet.',solar:'Ungefähres Sonnenhoroskop',knownChart:'Dein Horoskop nach Zeichen',partial:'Die Deutung konnte nicht abgeschlossen werden. Dein berechnetes Profil und der empfangene Text bleiben verfügbar.',toolkitPending:'Deine praktischen Impulse erscheinen, sobald die Deutung bereit ist.',seasonNote:'Basiert auf deinem Persönlichen Jahr. Aktuelle Planetentransite werden nicht berechnet.',shared:'Der verbindende Faden',tensions:'Raum für zwei Impulse',practical:'Im Alltag ausprobieren',
  },
  pt: {
    eyebrow:'Vários sistemas. Uma só pessoa.',headline:'Os padrões que fazem de você,',headlineEnd:'você.',description:'Explore como seus números, mapa natal e fase da vida se conectam.',discover:'Descubra seu mapa',sample:'Explore um exemplo',sampleLabel:'Leitura de exemplo',glimpse:'Uma pequena amostra',seal:'O selo do atlas / Um símbolo de conexão',insight:'Seu Caminho de Vida 7 e seu Sol em Escorpião compartilham o impulso de olhar além da superfície. Dê espaço à sua curiosidade.',beginnings:'Vamos começar pelas suas origens.',chapter:'Em que capítulo você está?',birthHelper:'Alguns detalhes para começar a conectar os fios.',chapterHelper:'A vida não cabe numa só caixa. Escolha tudo que combina com você.',unknown:'Sem hora de nascimento, omitimos Lua, ascendente e casas e mostramos um mapa solar aproximado.',privacy: 'Seu formulário fica nesta sessão. OpenRouter e seus provedores processam seu perfil para a interpretação. As leituras podem ficar na memória do servidor por até 24 horas.',reflection:'Uma ferramenta de reflexão, não uma previsão.',edit:'Editar dados',atlasOf:'O atlas de {name}.',sharePreview:'Prévia de compartilhamento',sharePrivacy:'Somente estes indicadores e o link serão copiados. Nome, data, hora e local de nascimento e contexto pessoal ficam excluídos.',copy:'Copiar resumo e link',close:'Fechar',ready:'Seu perfil calculado está pronto. Sua interpretação conectará estes fios.',chartPrecision:'Diagrama por signos: os marcadores mostram signos calculados, não graus exatos. Casas, aspectos e trânsitos atuais não são calculados.',solar:'Mapa solar aproximado',knownChart:'Seu mapa por signos',partial:'A interpretação não pôde ser concluída. Seu perfil calculado e o texto recebido continuam disponíveis.',toolkitPending:'Suas sugestões práticas aparecerão quando a interpretação estiver pronta.',seasonNote:'Baseado no seu Ano Pessoal. Não são calculados trânsitos planetários atuais.',shared:'O fio que conecta',tensions:'Espaço para dois impulsos',practical:'Leve à prática',
  },
  it: {
    eyebrow:'Molti sistemi. Una sola persona.',headline:'I tratti che ti rendono',headlineEnd:'te.',description:'Esplora come si collegano i tuoi numeri, il tema natale e la fase della tua vita.',discover:'Scopri il tuo atlante',sample:'Esplora un esempio',sampleLabel:'Lettura di esempio',glimpse:'Uno sguardo all’interno',seal:'Il sigillo dell’atlante / Un simbolo di connessione',insight:'Il tuo Percorso di Vita 7 e il Sole in Scorpione invitano a guardare sotto la superficie. Dai spazio alla tua curiosità.',beginnings:'Cominciamo dalle tue origini.',chapter:'In quale capitolo ti trovi?',birthHelper:'Qualche dettaglio per iniziare a collegare i fili.',chapterHelper:'La vita non entra in una sola casella. Scegli tutto ciò che ti rispecchia.',unknown:'Senza l’ora di nascita, omettiamo Luna, ascendente e case e mostriamo un tema solare approssimativo.',privacy: 'Il modulo resta in questa sessione. OpenRouter e i suoi fornitori elaborano il profilo per l’interpretazione. Le letture possono restare nella memoria del server fino a 24 ore.',reflection:'Uno strumento di riflessione, non una previsione.',edit:'Modifica i dati',atlasOf:'L’atlante di {name}.',sharePreview:'Anteprima di condivisione',sharePrivacy:'Verranno copiati solo questi indicatori e il link. Nome, data, ora, luogo di nascita e contesto personale sono esclusi.',copy:'Copia riepilogo e link',close:'Chiudi',ready:'Il tuo profilo calcolato è pronto. L’interpretazione collegherà questi fili.',chartPrecision:'Schema per segni: i marcatori mostrano i segni calcolati, non i gradi esatti. Case, aspetti e transiti attuali non vengono calcolati.',solar:'Tema solare approssimativo',knownChart:'Il tuo tema per segni',partial:'L’interpretazione non è stata completata. Il profilo calcolato e il testo ricevuto restano disponibili.',toolkitPending:'I tuoi spunti pratici appariranno quando l’interpretazione sarà pronta.',seasonNote:'Basato sul tuo Anno Personale. Non vengono calcolati transiti planetari attuali.',shared:'Il filo conduttore',tensions:'Spazio per due impulsi',practical:'Passa alla pratica',
  },
};
