import type { Messages } from "./en";
export const de: Messages = {
  meta:{title:"Cosmic Blueprint — Dein vollständiges kosmisches Profil",description:"Entdecke dein vereintes kosmisches Profil aus Numerologie, westlicher Astrologie, chinesischer Astrologie und Geburtshoroskop in einer einzigen Lesung.",ogTitle:"Cosmic Blueprint",ogDescription:"Dein vollständiges kosmisches Profil, vereint."},
  ui:{errorPrefix:"FEHLER:",okPrefix:"OK:",dismiss:"Schließen",timePlaceholder:"HH:MM"},
  header:{share:"Teilen",shareCopied:"Link kopiert",shareFailed:"Kopieren fehlgeschlagen",themeDark:"Dunkel",themeLight:"Hell"},
  landing:{badge:"Numerologie + Westliche Astrologie + Chinesisches Tierkreiszeichen",title1:"Kosmischer",title2:"Bauplan",subtitle:"Dein vollständiges kosmisches Profil, vereint.",subtitle2:"Drei alte Systeme. Eine persönliche Lesung.",privacy:"Deine Daten bleiben in deinem Browser. Wir speichern keine Geburtsdaten."},
  wizard:{step1Title:"Deine Geburtsdaten",step2Title:"Dein Lebenskontext",fullNameLabel:"Vollständiger Name (bei Geburt)",fullNamePlaceholder:"Gib deinen vollständigen Geburtsnamen ein",dobLabel:"Geburtsdatum",birthTimeLabel:"Geburtszeit",birthTimeOptional:"(falls bekannt)",iDontKnow:"Ich weiß es nicht",birthPlaceLabel:"Geburtsort (Stadt)",birthPlacePlaceholder:"Optional — ermöglicht die Berechnung des Aszendenten",lifeStageLabel:"Aktuelle Lebensphase",lifeStageHint:"(alles Zutreffende auswählen)",whatsOnYourMindLabel:"Was beschäftigt dich?",whatsOnYourMindOptional:"(optional)",whatsOnYourMindPlaceholder:"Ein oder zwei Sätze darüber, was gerade in deinem Leben passiert...",genderLabel:"Geschlecht",genderOptional:"(optional)",genderOptions:{female:"Weiblich",male:"Männlich",nonBinary:"Nicht-binär",preferNotToSay:"Möchte ich nicht angeben"},back:"Zurück",continue:"Weiter",reveal:"Meinen kosmischen Bauplan zeigen",loading:"Dein Bauplan wird erstellt...",step:"Schritt",errNameRequired:"Gib deinen Namen ein",errDobRequired:"Gib dein Geburtsdatum ein",errDobRange:"Das Datum muss zwischen 1900 und heute liegen",errBirthTime:"Gib eine gültige Uhrzeit ein (HH:MM, 24 Std.) oder markiere Ich weiß es nicht",errLifeStageRequired:"Wähle mindestens eine Lebensphase"},
  lifeStages:{exploring:"Ich erkunde das Leben",building_career:"Ich baue meine Karriere auf",in_relationship:"In einer Beziehung",married:"Verheiratet",parent:"Elternteil",empty_nester:"Kinder aus dem Haus",retired:"Im Ruhestand",prefer_not_to_say:"Möchte ich nicht angeben"},
  results:{newReading:"Neue Lesung",title:"Kosmischer Bauplan",forPerson:"für {name}",loadingMessage:"Dein kosmischer Bauplan wird erstellt...",errorTitle:"Etwas ist schiefgelaufen",startOver:"Neu beginnen",cosmicSnapshotLabel:"Deine kosmische Zusammenfassung",generateAnother:"Weitere Lesung erstellen",closingMessage:"Möge diese Karte deinen Weg gut begleiten.",geocodeWarning:"Geburtsort nicht erkannt — Sonnenhoroskop wird angezeigt"},
  sections:{numbersTitle:"Die Zahlen",numbersSubtitle:"Dein Numerologieprofil zeigt die mathematische Signatur deines Lebens",starMapTitle:"Deine Sternenkarte",starMapSubtitle:"Westliche Astrologie zeigt deine himmlische Identität",easternMirrorTitle:"Dein östlicher Spiegel",easternMirrorSubtitle:"Chinesische Astrologie spiegelt deine kosmische Tiernatur",unifiedReadingTitle:"Die vereinte Lesung",unifiedReadingSubtitle:"Wo sich all deine kosmischen Fäden verbinden",currentSeasonTitle:"Deine aktuelle Phase",currentSeasonSubtitle:"Was der Kosmos gerade in deinem Leben aktiviert",cosmicToolkitTitle:"Dein kosmischer Werkzeugkasten",cosmicToolkitSubtitle:"Praktische Impulse aus deinem vollständigen kosmischen Profil"},
  numerology:{lifePath:"Lebensweg",expression:"Ausdruck",soulUrge:"Seelenwunsch",personality:"Persönlichkeit",personalYear:"Persönliches Jahr"},
  western:{sunSign:"Sonnenzeichen",moonSign:"Mondzeichen",risingSign:"Aszendent",natalChart:"Geburtshoroskop",solarChartNote:"Sonnenhoroskop — Geburtszeit für Mond und Aszendent angeben",birthTimeNote:"Gib Geburtszeit und -ort an, um Mondzeichen, Aszendent und präzisere Deutungen zu erhalten.",decan:"Dekan",element:"Element",modality:"Qualität",rulingPlanet:"Herrscherplanet",chartSun:"SONNE",chartMoon:"MOND",chartAsc:"ASZ"},
  chinese:{animalName:"Der {animal}",bestWith:"Beste Verbindung",challenging:"Herausfordernd",elementLabel:"Element {element}"},
  analysis:{errorMessage:"Die KI-Analyse konnte derzeit nicht erstellt werden.",tryAgain:"Erneut versuchen",personalYear:"Persönliches Jahr",generating:"Deine Lesung wird geschrieben..."},
};
