import type { Messages } from "./en";
export const es: Messages = {
  meta:{title:"Cosmic Blueprint — Tu perfil cósmico completo",description:"Descubre tu perfil cósmico unificado combinando numerología, astrología occidental, astrología china y carta natal en una sola lectura.",ogTitle:"Cosmic Blueprint",ogDescription:"Tu perfil cósmico completo, unificado."},
  ui:{errorPrefix:"ERROR:",okPrefix:"OK:",dismiss:"Cerrar",timePlaceholder:"HH:MM"},
  header:{share:"Compartir",shareCopied:"Enlace copiado",shareFailed:"No se pudo copiar",themeDark:"Oscuro",themeLight:"Claro"},
  landing:{badge:"Numerología + Astrología Occidental + Zodiaco Chino",title1:"Mapa",title2:"Cósmico",subtitle:"Tu perfil cósmico completo, unificado.",subtitle2:"Tres sistemas antiguos. Una lectura personal.",privacy:"Tus datos permanecen en tu navegador. No almacenamos tus datos de nacimiento."},
  wizard:{step1Title:"Tus datos de nacimiento",step2Title:"Tu contexto vital",fullNameLabel:"Nombre completo (al nacer)",fullNamePlaceholder:"Introduce tu nombre completo de nacimiento",dobLabel:"Fecha de nacimiento",birthTimeLabel:"Hora de nacimiento",birthTimeOptional:"(si la sabes)",iDontKnow:"No lo sé",birthPlaceLabel:"Lugar de nacimiento (ciudad)",birthPlacePlaceholder:"Opcional — permite calcular el ascendente",lifeStageLabel:"Etapa vital actual",lifeStageHint:"(elige todas las que correspondan)",whatsOnYourMindLabel:"¿Qué tienes en mente?",whatsOnYourMindOptional:"(opcional)",whatsOnYourMindPlaceholder:"Una o dos frases sobre lo que está pasando en tu vida ahora...",genderLabel:"Género",genderOptional:"(opcional)",genderOptions:{female:"Mujer",male:"Hombre",nonBinary:"No binario",preferNotToSay:"Prefiero no decirlo"},back:"Atrás",continue:"Continuar",reveal:"Revelar mi mapa cósmico",loading:"Trazando tu mapa...",step:"Paso",errNameRequired:"Introduce tu nombre",errDobRequired:"Introduce tu fecha de nacimiento",errDobRange:"La fecha debe estar entre 1900 y hoy",errBirthTime:"Introduce una hora válida (HH:MM, 24 h) o marca No lo sé",errLifeStageRequired:"Elige al menos una etapa vital"},
  lifeStages:{exploring:"Explorando la vida",building_career:"Construyendo mi carrera",in_relationship:"En una relación",married:"Casado/a",parent:"Madre o padre",empty_nester:"Nido vacío",retired:"Jubilado/a",prefer_not_to_say:"Prefiero no decirlo"},
  results:{newReading:"Nueva lectura",title:"Mapa Cósmico",forPerson:"para {name}",loadingMessage:"Trazando tu mapa cósmico...",errorTitle:"Algo salió mal",startOver:"Empezar de nuevo",cosmicSnapshotLabel:"Tu resumen cósmico",generateAnother:"Generar otra lectura",closingMessage:"Que este mapa acompañe bien tu camino.",geocodeWarning:"No se reconoció el lugar de nacimiento — mostrando carta solar"},
  sections:{numbersTitle:"Los números",numbersSubtitle:"Tu perfil numerológico revela la firma matemática de tu vida",starMapTitle:"Tu mapa estelar",starMapSubtitle:"La astrología occidental revela tu identidad celeste",easternMirrorTitle:"Tu espejo oriental",easternMirrorSubtitle:"La astrología china refleja tu naturaleza animal cósmica",unifiedReadingTitle:"La lectura unificada",unifiedReadingSubtitle:"Donde todos tus hilos cósmicos se entrelazan",currentSeasonTitle:"Tu momento actual",currentSeasonSubtitle:"Lo que el cosmos está activando ahora en tu vida",cosmicToolkitTitle:"Tu caja de herramientas cósmica",cosmicToolkitSubtitle:"Ideas prácticas de tu perfil cósmico completo"},
  numerology:{lifePath:"Camino de Vida",expression:"Expresión",soulUrge:"Impulso del Alma",personality:"Personalidad",personalYear:"Año Personal"},
  western:{sunSign:"Signo solar",moonSign:"Signo lunar",risingSign:"Ascendente",natalChart:"Carta natal",solarChartNote:"Carta solar — añade la hora de nacimiento para luna y ascendente",birthTimeNote:"Añade hora y lugar de nacimiento para obtener luna, ascendente y una lectura más precisa.",decan:"Decanato",element:"Elemento",modality:"Modalidad",rulingPlanet:"Planeta regente",chartSun:"SOL",chartMoon:"LUNA",chartAsc:"ASC"},
  chinese:{animalName:"El {animal}",bestWith:"Más compatible",challenging:"Desafiante",elementLabel:"Elemento {element}"},
  analysis:{errorMessage:"No se pudo generar el análisis de IA en este momento.",tryAgain:"Intentar de nuevo",personalYear:"Año Personal",generating:"Escribiendo tu lectura..."},
};
