import type { Messages } from "./en";
export const fr: Messages = {
  meta:{title:"Cosmic Blueprint — Votre profil cosmique complet",description:"Découvrez votre profil cosmique unifié mêlant numérologie, astrologie occidentale, astrologie chinoise et thème natal dans une seule lecture.",ogTitle:"Cosmic Blueprint",ogDescription:"Votre profil cosmique complet, unifié."},
  ui:{errorPrefix:"ERREUR :",okPrefix:"OK :",dismiss:"Fermer",timePlaceholder:"HH:MM"},
  header:{share:"Partager",shareCopied:"Lien copié",shareFailed:"Échec de la copie",themeDark:"Sombre",themeLight:"Clair"},
  landing:{badge:"Numérologie + Astrologie occidentale + Zodiaque chinois",title1:"Carte",title2:"Cosmique",subtitle:"Votre profil cosmique complet, unifié.",subtitle2:"Trois systèmes anciens. Une lecture personnelle.",privacy:"Vos données restent dans votre navigateur. Nous ne stockons pas vos informations de naissance."},
  wizard:{step1Title:"Vos informations de naissance",step2Title:"Votre contexte de vie",fullNameLabel:"Nom complet (à la naissance)",fullNamePlaceholder:"Saisissez votre nom complet de naissance",dobLabel:"Date de naissance",birthTimeLabel:"Heure de naissance",birthTimeOptional:"(si connue)",iDontKnow:"Je ne sais pas",birthPlaceLabel:"Lieu de naissance (ville)",birthPlacePlaceholder:"Facultatif — permet de calculer l'ascendant",lifeStageLabel:"Étape de vie actuelle",lifeStageHint:"(sélectionnez tout ce qui s'applique)",whatsOnYourMindLabel:"Qu'avez-vous en tête ?",whatsOnYourMindOptional:"(facultatif)",whatsOnYourMindPlaceholder:"Une ou deux phrases sur ce qui se passe dans votre vie en ce moment...",genderLabel:"Genre",genderOptional:"(facultatif)",genderOptions:{female:"Femme",male:"Homme",nonBinary:"Non binaire",preferNotToSay:"Je préfère ne pas répondre"},back:"Retour",continue:"Continuer",reveal:"Révéler ma carte cosmique",loading:"Cartographie en cours...",step:"Étape",errNameRequired:"Saisissez votre nom",errDobRequired:"Saisissez votre date de naissance",errDobRange:"La date doit être comprise entre 1900 et aujourd'hui",errBirthTime:"Saisissez une heure valide (HH:MM, 24 h) ou cochez Je ne sais pas",errLifeStageRequired:"Sélectionnez au moins une étape de vie"},
  lifeStages:{exploring:"J'explore la vie",building_career:"Je construis ma carrière",in_relationship:"En couple",married:"Marié(e)",parent:"Parent",empty_nester:"Enfants partis du foyer",retired:"Retraité(e)",prefer_not_to_say:"Je préfère ne pas répondre"},
  results:{newReading:"Nouvelle lecture",title:"Carte Cosmique",forPerson:"pour {name}",loadingMessage:"Cartographie de votre profil cosmique...",errorTitle:"Un problème est survenu",startOver:"Recommencer",cosmicSnapshotLabel:"Votre synthèse cosmique",generateAnother:"Générer une autre lecture",closingMessage:"Que cette carte vous accompagne utilement sur votre chemin.",geocodeWarning:"Lieu de naissance non reconnu — affichage d'une carte solaire"},
  sections:{numbersTitle:"Les nombres",numbersSubtitle:"Votre profil numérologique révèle la signature mathématique de votre vie",starMapTitle:"Votre carte céleste",starMapSubtitle:"L'astrologie occidentale révèle votre identité céleste",easternMirrorTitle:"Votre miroir oriental",easternMirrorSubtitle:"L'astrologie chinoise reflète votre nature animale cosmique",unifiedReadingTitle:"La lecture unifiée",unifiedReadingSubtitle:"Là où tous vos fils cosmiques se rejoignent",currentSeasonTitle:"Votre période actuelle",currentSeasonSubtitle:"Ce que le cosmos active dans votre vie en ce moment",cosmicToolkitTitle:"Votre boîte à outils cosmique",cosmicToolkitSubtitle:"Des pistes pratiques tirées de votre profil cosmique complet"},
  numerology:{lifePath:"Chemin de Vie",expression:"Expression",soulUrge:"Élan de l'Âme",personality:"Personnalité",personalYear:"Année Personnelle"},
  western:{sunSign:"Signe solaire",moonSign:"Signe lunaire",risingSign:"Ascendant",natalChart:"Thème natal",solarChartNote:"Carte solaire — indiquez l'heure de naissance pour la lune et l'ascendant",birthTimeNote:"Indiquez votre heure et lieu de naissance pour obtenir la lune, l'ascendant et une lecture plus précise.",decan:"Décan",element:"Élément",modality:"Modalité",rulingPlanet:"Planète maîtresse",chartSun:"SOLEIL",chartMoon:"LUNE",chartAsc:"ASC"},
  chinese:{animalName:"Le {animal}",bestWith:"Meilleure affinité",challenging:"Plus difficile",elementLabel:"Élément {element}"},
  analysis:{errorMessage:"L'analyse IA n'a pas pu être générée pour le moment.",tryAgain:"Réessayer",personalYear:"Année Personnelle",generating:"Rédaction de votre lecture..."},
};
