import type { Messages } from "./en";
export const it: Messages = {
  meta:{title:"Cosmic Blueprint — Il tuo profilo cosmico completo",description:"Scopri il tuo profilo cosmico unificato combinando numerologia, astrologia occidentale, astrologia cinese e tema natale in un'unica lettura.",ogTitle:"Cosmic Blueprint",ogDescription:"Il tuo profilo cosmico completo, unificato."},
  ui:{errorPrefix:"ERRORE:",okPrefix:"OK:",dismiss:"Chiudi",timePlaceholder:"HH:MM"},
  header:{share:"Condividi",shareCopied:"Link copiato",shareFailed:"Copia non riuscita",themeDark:"Scuro",themeLight:"Chiaro"},
  landing:{badge:"Numerologia + Astrologia Occidentale + Zodiaco Cinese",title1:"Mappa",title2:"Cosmica",subtitle:"Il tuo profilo cosmico completo, unificato.",subtitle2:"Tre sistemi antichi. Una lettura personale.",privacy:"I tuoi dati restano nel browser. Non memorizziamo i dati di nascita."},
  wizard:{step1Title:"I tuoi dati di nascita",step2Title:"Il tuo contesto di vita",fullNameLabel:"Nome completo (alla nascita)",fullNamePlaceholder:"Inserisci il tuo nome completo di nascita",dobLabel:"Data di nascita",birthTimeLabel:"Ora di nascita",birthTimeOptional:"(se conosciuta)",iDontKnow:"Non lo so",birthPlaceLabel:"Luogo di nascita (città)",birthPlacePlaceholder:"Facoltativo — consente di calcolare l'ascendente",lifeStageLabel:"Fase di vita attuale",lifeStageHint:"(seleziona tutte quelle pertinenti)",whatsOnYourMindLabel:"Cosa hai in mente?",whatsOnYourMindOptional:"(facoltativo)",whatsOnYourMindPlaceholder:"Una o due frasi su ciò che sta accadendo nella tua vita in questo momento...",genderLabel:"Genere",genderOptional:"(facoltativo)",genderOptions:{female:"Donna",male:"Uomo",nonBinary:"Non binario",preferNotToSay:"Preferisco non dirlo"},back:"Indietro",continue:"Continua",reveal:"Rivela la mia mappa cosmica",loading:"Sto tracciando la tua mappa...",step:"Passo",errNameRequired:"Inserisci il tuo nome",errDobRequired:"Inserisci la tua data di nascita",errDobRange:"La data deve essere compresa tra il 1900 e oggi",errBirthTime:"Inserisci un'ora valida (HH:MM, 24 ore) oppure seleziona Non lo so",errLifeStageRequired:"Seleziona almeno una fase di vita"},
  lifeStages:{exploring:"Sto esplorando la vita",building_career:"Sto costruendo la carriera",in_relationship:"In una relazione",married:"Sposato/a",parent:"Genitore",empty_nester:"Figli fuori casa",retired:"In pensione",prefer_not_to_say:"Preferisco non dirlo"},
  results:{newReading:"Nuova lettura",title:"Mappa Cosmica",forPerson:"per {name}",loadingMessage:"Sto tracciando la tua mappa cosmica...",errorTitle:"Qualcosa è andato storto",startOver:"Ricomincia",cosmicSnapshotLabel:"La tua sintesi cosmica",generateAnother:"Genera un'altra lettura",closingMessage:"Che questa mappa accompagni bene il tuo percorso.",geocodeWarning:"Luogo di nascita non riconosciuto — viene mostrata la carta solare"},
  sections:{numbersTitle:"I numeri",numbersSubtitle:"Il tuo profilo numerologico rivela la firma matematica della tua vita",starMapTitle:"La tua mappa stellare",starMapSubtitle:"L'astrologia occidentale rivela la tua identità celeste",easternMirrorTitle:"Il tuo specchio orientale",easternMirrorSubtitle:"L'astrologia cinese riflette la tua natura animale cosmica",unifiedReadingTitle:"La lettura unificata",unifiedReadingSubtitle:"Dove tutti i tuoi fili cosmici si intrecciano",currentSeasonTitle:"La tua fase attuale",currentSeasonSubtitle:"Ciò che il cosmo sta attivando nella tua vita in questo momento",cosmicToolkitTitle:"Il tuo kit cosmico",cosmicToolkitSubtitle:"Indicazioni pratiche dal tuo profilo cosmico completo"},
  numerology:{lifePath:"Percorso di Vita",expression:"Espressione",soulUrge:"Desiderio dell'Anima",personality:"Personalità",personalYear:"Anno Personale"},
  western:{sunSign:"Segno solare",moonSign:"Segno lunare",risingSign:"Ascendente",natalChart:"Tema natale",solarChartNote:"Carta solare — inserisci l'ora di nascita per luna e ascendente",birthTimeNote:"Inserisci ora e luogo di nascita per ottenere segno lunare, ascendente e letture più precise.",decan:"Decano",element:"Elemento",modality:"Modalità",rulingPlanet:"Pianeta dominante",chartSun:"SOLE",chartMoon:"LUNA",chartAsc:"ASC"},
  chinese:{animalName:"Il {animal}",bestWith:"Più compatibile",challenging:"Impegnativo",elementLabel:"Elemento {element}"},
  analysis:{errorMessage:"Al momento non è stato possibile generare l'analisi IA.",tryAgain:"Riprova",personalYear:"Anno Personale",generating:"Sto scrivendo la tua lettura..."},
};
