import type { Messages } from "./en";
export const pt: Messages = {
  meta:{title:"Cosmic Blueprint — O seu perfil cósmico completo",description:"Descubra o seu perfil cósmico unificado combinando numerologia, astrologia ocidental, astrologia chinesa e mapa natal numa única leitura.",ogTitle:"Cosmic Blueprint",ogDescription:"O seu perfil cósmico completo, unificado."},
  ui:{errorPrefix:"ERRO:",okPrefix:"OK:",dismiss:"Fechar",timePlaceholder:"HH:MM"},
  header:{share:"Partilhar",shareCopied:"Ligação copiada",shareFailed:"Falha ao copiar",themeDark:"Escuro",themeLight:"Claro"},
  landing:{badge:"Numerologia + Astrologia Ocidental + Zodíaco Chinês",title1:"Mapa",title2:"Cósmico",subtitle:"O seu perfil cósmico completo, unificado.",subtitle2:"Três sistemas antigos. Uma leitura pessoal.",privacy:"Os seus dados permanecem no navegador. Não guardamos os seus dados de nascimento."},
  wizard:{step1Title:"Os seus dados de nascimento",step2Title:"O seu contexto de vida",fullNameLabel:"Nome completo (à nascença)",fullNamePlaceholder:"Introduza o seu nome completo de nascimento",dobLabel:"Data de nascimento",birthTimeLabel:"Hora de nascimento",birthTimeOptional:"(se souber)",iDontKnow:"Não sei",birthPlaceLabel:"Local de nascimento (cidade)",birthPlacePlaceholder:"Opcional — permite calcular o ascendente",lifeStageLabel:"Fase atual da vida",lifeStageHint:"(selecione todas as aplicáveis)",whatsOnYourMindLabel:"O que tem em mente?",whatsOnYourMindOptional:"(opcional)",whatsOnYourMindPlaceholder:"Uma ou duas frases sobre o que está a acontecer na sua vida agora...",genderLabel:"Género",genderOptional:"(opcional)",genderOptions:{female:"Feminino",male:"Masculino",nonBinary:"Não binário",preferNotToSay:"Prefiro não dizer"},back:"Voltar",continue:"Continuar",reveal:"Revelar o meu mapa cósmico",loading:"A mapear o seu perfil...",step:"Passo",errNameRequired:"Introduza o seu nome",errDobRequired:"Introduza a sua data de nascimento",errDobRange:"A data deve estar entre 1900 e hoje",errBirthTime:"Introduza uma hora válida (HH:MM, 24 h) ou assinale Não sei",errLifeStageRequired:"Selecione pelo menos uma fase da vida"},
  lifeStages:{exploring:"A explorar a vida",building_career:"A construir a carreira",in_relationship:"Numa relação",married:"Casado/a",parent:"Pai ou mãe",empty_nester:"Filhos já saíram de casa",retired:"Reformado/a",prefer_not_to_say:"Prefiro não dizer"},
  results:{newReading:"Nova leitura",title:"Mapa Cósmico",forPerson:"para {name}",loadingMessage:"A mapear o seu perfil cósmico...",errorTitle:"Algo correu mal",startOver:"Recomeçar",cosmicSnapshotLabel:"O seu resumo cósmico",generateAnother:"Gerar outra leitura",closingMessage:"Que este mapa acompanhe bem a sua jornada.",geocodeWarning:"Local de nascimento não reconhecido — a mostrar mapa solar"},
  sections:{numbersTitle:"Os números",numbersSubtitle:"O seu perfil numerológico revela a assinatura matemática da sua vida",starMapTitle:"O seu mapa estelar",starMapSubtitle:"A astrologia ocidental revela a sua identidade celeste",easternMirrorTitle:"O seu espelho oriental",easternMirrorSubtitle:"A astrologia chinesa reflete a sua natureza animal cósmica",unifiedReadingTitle:"A leitura unificada",unifiedReadingSubtitle:"Onde todos os seus fios cósmicos se entrelaçam",currentSeasonTitle:"A sua fase atual",currentSeasonSubtitle:"O que o cosmos está a ativar na sua vida agora",cosmicToolkitTitle:"A sua caixa de ferramentas cósmica",cosmicToolkitSubtitle:"Sugestões práticas do seu perfil cósmico completo"},
  numerology:{lifePath:"Caminho de Vida",expression:"Expressão",soulUrge:"Desejo da Alma",personality:"Personalidade",personalYear:"Ano Pessoal"},
  western:{sunSign:"Signo solar",moonSign:"Signo lunar",risingSign:"Ascendente",natalChart:"Mapa natal",solarChartNote:"Mapa solar — indique a hora de nascimento para lua e ascendente",birthTimeNote:"Indique hora e local de nascimento para obter signo lunar, ascendente e leituras mais precisas.",decan:"Decanato",element:"Elemento",modality:"Modalidade",rulingPlanet:"Planeta regente",chartSun:"SOL",chartMoon:"LUA",chartAsc:"ASC"},
  chinese:{animalName:"O {animal}",bestWith:"Mais compatível",challenging:"Desafiante",elementLabel:"Elemento {element}"},
  analysis:{errorMessage:"A análise de IA não pôde ser gerada neste momento.",tryAgain:"Tentar novamente",personalYear:"Ano Pessoal",generating:"A escrever a sua leitura..."},
};
