import type { Messages } from "./en";

export const tr: Messages = {
  meta: { title: "Cosmic Blueprint — Eksiksiz Kozmik Profiliniz", description: "Numeroloji, Batı astrolojisi, Çin astrolojisi ve doğum haritası analizini tek bir sentezde birleştiren kozmik profilinizi keşfedin.", ogTitle: "Cosmic Blueprint", ogDescription: "Eksiksiz kozmik profiliniz, tek bir okumada." },
  ui: { errorPrefix: "HATA:", okPrefix: "TAMAM:", dismiss: "Kapat", timePlaceholder: "SS:DD" },
  header: { share: "Paylaş", shareCopied: "Bağlantı kopyalandı", shareFailed: "Kopyalanamadı", themeDark: "Koyu", themeLight: "Açık" },
  landing: { badge: "Numeroloji + Batı Astrolojisi + Çin Burçları", title1: "Kozmik", title2: "Harita", subtitle: "Eksiksiz kozmik profiliniz, tek bir okumada.", subtitle2: "Üç kadim sistem. Tek bir kişisel okuma.", privacy: "Verileriniz tarayıcınızda kalır. Doğum bilgilerinizi saklamıyoruz." },
  wizard: { step1Title: "Doğum Bilgileriniz", step2Title: "Yaşam Bağlamınız", fullNameLabel: "Tam adınız (doğumdaki haliyle)", fullNamePlaceholder: "Doğumdaki tam adınızı girin", dobLabel: "Doğum tarihi", birthTimeLabel: "Doğum saati", birthTimeOptional: "(biliniyorsa)", iDontKnow: "Bilmiyorum", birthPlaceLabel: "Doğum yeri (şehir)", birthPlacePlaceholder: "İsteğe bağlı — yükselen burç hesabını etkinleştirir", lifeStageLabel: "Mevcut yaşam dönemi", lifeStageHint: "(uygun olanların tümünü seçin)", whatsOnYourMindLabel: "Aklınızda ne var?", whatsOnYourMindOptional: "(isteğe bağlı)", whatsOnYourMindPlaceholder: "Hayatınızda şu an neler oluyor, bir iki cümleyle anlatın...", genderLabel: "Cinsiyet", genderOptional: "(isteğe bağlı)", genderOptions: { female: "Kadın", male: "Erkek", nonBinary: "Non-binary", preferNotToSay: "Belirtmek istemiyorum" }, back: "Geri", continue: "Devam", reveal: "Kozmik Haritamı Göster", loading: "Kozmik haritanız çıkarılıyor...", step: "Adım", errNameRequired: "Adınızı girin", errDobRequired: "Doğum tarihinizi girin", errDobRange: "Tarih 1900 ile bugün arasında olmalı", errBirthTime: "Geçerli bir saat girin (SS:DD, 24 saat) veya Bilmiyorum'u işaretleyin", errLifeStageRequired: "En az bir yaşam dönemi seçin" },
  lifeStages: { exploring: "Hayatı keşfediyorum", building_career: "Kariyer kuruyorum", in_relationship: "Bir ilişkim var", married: "Evliyim", parent: "Ebeveynim", empty_nester: "Çocuklar evden ayrıldı", retired: "Emekliyim", prefer_not_to_say: "Belirtmek istemiyorum" },
  results: { newReading: "Yeni Okuma", title: "Kozmik Harita", forPerson: "{name} için", loadingMessage: "Kozmik haritanız çıkarılıyor...", errorTitle: "Bir sorun oluştu", startOver: "Baştan Başla", cosmicSnapshotLabel: "Kozmik Özetiniz", generateAnother: "Başka Bir Okuma Oluştur", closingMessage: "Bu harita yolculuğunuza ışık tutsun.", geocodeWarning: "Doğum yeri tanınamadı — güneş haritası gösteriliyor" },
  sections: { numbersTitle: "Sayılar", numbersSubtitle: "Numeroloji profiliniz hayatınızın matematiksel imzasını ortaya koyar", starMapTitle: "Yıldız Haritanız", starMapSubtitle: "Batı astrolojisi göksel kimliğinizi ortaya koyar", easternMirrorTitle: "Doğu Aynanız", easternMirrorSubtitle: "Çin astrolojisi kozmik hayvan doğanızı yansıtır", unifiedReadingTitle: "Birleşik Okuma", unifiedReadingSubtitle: "Tüm kozmik ipliklerinizin bir araya geldiği yer", currentSeasonTitle: "Bu Dönem Sizin İçin", currentSeasonSubtitle: "Kozmosun hayatınızda şu an neyi harekete geçirdiği", cosmicToolkitTitle: "Kozmik Araç Çantanız", cosmicToolkitSubtitle: "Eksiksiz kozmik profilinizden pratik çıkarımlar" },
  numerology: { lifePath: "Yaşam Yolu", expression: "İfade", soulUrge: "Ruh Dürtüsü", personality: "Kişilik", personalYear: "Kişisel Yıl" },
  western: { sunSign: "Güneş Burcu", moonSign: "Ay Burcu", risingSign: "Yükselen Burç", natalChart: "Doğum Haritası", solarChartNote: "Güneş haritası — ay ve yükselen burç için doğum saatinizi girin", birthTimeNote: "Ay burcu, yükselen burç ve daha hassas okumalar için doğum saatinizi ve yerinizi girin.", decan: "Dekan", element: "Element", modality: "Nitelik", rulingPlanet: "Yönetici Gezegen", chartSun: "GÜNEŞ", chartMoon: "AY", chartAsc: "YÜK" },
  chinese: { animalName: "{animal}", bestWith: "En Uyumlu", challenging: "Zorlayıcı", elementLabel: "{element} Elementi" },
  analysis: { errorMessage: "Yapay zekâ analizi şu anda oluşturulamadı.", tryAgain: "Tekrar Dene", personalYear: "Kişisel Yıl", generating: "Okumanız yazılıyor..." },
};
